import { useState, useCallback } from 'react'
import {
  Button,
  Label,
  Input,
  useToast,
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  Separator,
} from '@repo/ui'
import { TonConnectWalletBridge } from '../utils/ton-connect/wallet-bridge.js'

interface TonConnectInfoProps {
  httpBridge: TonConnectWalletBridge
  isConnected: boolean
}

export function TonConnectInfo({
  httpBridge,
  isConnected,
}: TonConnectInfoProps) {
  const [connectionUrl, setConnectionUrl] = useState('')
  const [isConnecting, setIsConnecting] = useState(false)
  const { toast } = useToast()

  const handleConnect = useCallback(async () => {
    if (!connectionUrl.trim()) {
      toast({
        title: 'Invalid URL',
        description: 'Please enter a valid connection URL',
        variant: 'destructive',
      })
      return
    }

    try {
      setIsConnecting(true)
      await httpBridge.handleConnectionUrl(connectionUrl)
      toast({
        title: '✅ Connection processed',
        description: 'dApp connection request has been processed successfully',
      })
      setConnectionUrl('')
    } catch (error) {
      toast({
        title: 'Connection failed',
        description: error instanceof Error ? error.message : 'Unknown error',
        variant: 'destructive',
      })
    } finally {
      setIsConnecting(false)
    }
  }, [connectionUrl, httpBridge, toast])

  if (!isConnected) {
    return null
  }

  return (
    <div className="max-w-4xl mx-auto px-6">
      <Card className="border-0 shadow-lg bg-gradient-to-br from-white to-gray-50/50 dark:from-gray-900 dark:to-gray-800/50">
        <CardHeader>
          <div className="flex items-center space-x-3">
            <div className="w-10 h-10 bg-gradient-to-br from-purple-500 to-purple-600 rounded-lg flex items-center justify-center">
              <span className="text-white text-lg">🔗</span>
            </div>
            <div>
              <CardTitle className="text-xl">TON Connect Bridge</CardTitle>
              <p className="text-sm text-muted-foreground">
                Connect with dApps using TON Connect protocol
              </p>
            </div>
          </div>
        </CardHeader>

        <CardContent className="space-y-6">
          {/* Connection Status */}
          <div className="p-4 bg-gradient-to-br from-green-50 to-green-100 dark:from-green-950/30 dark:to-green-900/30 rounded-xl border border-green-200 dark:border-green-800">
            <div className="flex items-center space-x-3">
              <div className="w-8 h-8 bg-green-500 rounded-full flex items-center justify-center">
                <span className="text-white text-sm">✓</span>
              </div>
              <div>
                <p className="font-medium text-green-800 dark:text-green-200">
                  Bridge Active
                </p>
                <p className="text-sm text-green-700 dark:text-green-300">
                  Ready to receive dApp connection requests
                </p>
              </div>
            </div>
          </div>

          {/* dApp Connection */}
          <div className="space-y-4">
            <div className="flex items-center space-x-2">
              <div className="w-6 h-6 bg-blue-500 rounded-full flex items-center justify-center">
                <span className="text-white text-xs">1</span>
              </div>
              <h3 className="font-semibold text-lg">Connect to dApp</h3>
            </div>

            <div className="p-6 bg-gradient-to-br from-blue-50 to-blue-100 dark:from-blue-950/30 dark:to-blue-900/30 rounded-xl border border-blue-200 dark:border-blue-800">
              <div className="space-y-4">
                <div>
                  <Label
                    htmlFor="connectionUrl"
                    className="text-sm font-medium text-blue-800 dark:text-blue-200"
                  >
                    dApp Connection URL
                  </Label>
                  <p className="text-xs text-blue-700 dark:text-blue-300 mt-1 mb-3">
                    Paste the connection URL generated by the dApp
                  </p>
                  <Input
                    id="connectionUrl"
                    value={connectionUrl}
                    onChange={(e) => setConnectionUrl(e.target.value)}
                    placeholder="ton-connect://connect?v=2&id=..."
                    className="font-mono text-sm"
                  />
                </div>

                <Button
                  onClick={handleConnect}
                  disabled={!connectionUrl.trim() || isConnecting}
                  className="w-full bg-gradient-to-r from-blue-500 to-blue-600 hover:from-blue-600 hover:to-blue-700 text-white shadow-lg"
                >
                  {isConnecting ? (
                    <>
                      <div className="animate-spin rounded-full h-4 w-4 border-2 border-white border-t-transparent mr-2" />
                      Connecting...
                    </>
                  ) : (
                    <>🔗 Connect to dApp</>
                  )}
                </Button>
              </div>
            </div>
          </div>

          <Separator />

          {/* How to Use Guide */}
          <div className="space-y-4">
            <div className="flex items-center space-x-2">
              <div className="w-6 h-6 bg-amber-500 rounded-full flex items-center justify-center">
                <span className="text-white text-xs">?</span>
              </div>
              <h3 className="font-semibold text-lg">How to Connect</h3>
            </div>

            <div className="p-6 bg-gradient-to-br from-amber-50 to-amber-100 dark:from-amber-950/20 dark:to-amber-900/20 rounded-xl border border-amber-200 dark:border-amber-800">
              <ol className="space-y-3 text-sm">
                <li className="flex items-start space-x-3">
                  <span className="flex-shrink-0 w-6 h-6 bg-amber-500 text-white rounded-full flex items-center justify-center text-xs font-medium">
                    1
                  </span>
                  <span className="text-amber-800 dark:text-amber-200">
                    Go to any TON dApp and click{' '}
                    <strong>"Connect Wallet"</strong>
                  </span>
                </li>
                <li className="flex items-start space-x-3">
                  <span className="flex-shrink-0 w-6 h-6 bg-amber-500 text-white rounded-full flex items-center justify-center text-xs font-medium">
                    2
                  </span>
                  <span className="text-amber-800 dark:text-amber-200">
                    Copy the connection URL generated by the dApp
                  </span>
                </li>
                <li className="flex items-start space-x-3">
                  <span className="flex-shrink-0 w-6 h-6 bg-amber-500 text-white rounded-full flex items-center justify-center text-xs font-medium">
                    3
                  </span>
                  <span className="text-amber-800 dark:text-amber-200">
                    Paste it in the field above and click{' '}
                    <strong>"Connect to dApp"</strong>
                  </span>
                </li>
                <li className="flex items-start space-x-3">
                  <span className="flex-shrink-0 w-6 h-6 bg-amber-500 text-white rounded-full flex items-center justify-center text-xs font-medium">
                    4
                  </span>
                  <span className="text-amber-800 dark:text-amber-200">
                    Approve the connection request in the confirmation dialog
                  </span>
                </li>
              </ol>
            </div>
          </div>

          <Separator />

          {/* Technical Details */}
          <details className="group">
            <summary className="flex items-center justify-between cursor-pointer list-none">
              <div className="flex items-center space-x-2">
                <div className="w-6 h-6 bg-gray-500 rounded-full flex items-center justify-center">
                  <span className="text-white text-xs">⚙️</span>
                </div>
                <h3 className="font-semibold text-lg">Technical Details</h3>
              </div>
              <span className="text-muted-foreground group-open:rotate-90 transition-transform">
                ▶️
              </span>
            </summary>

            <div className="mt-4 space-y-4">
              <div className="grid md:grid-cols-2 gap-4">
                <div className="p-4 bg-white/60 dark:bg-gray-800/60 rounded-lg border">
                  <Label className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
                    Bridge URL
                  </Label>
                  <p className="text-sm font-mono mt-1 break-all leading-relaxed">
                    {httpBridge.getBridgeUrl()}
                  </p>
                </div>

                <div className="p-4 bg-white/60 dark:bg-gray-800/60 rounded-lg border">
                  <Label className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
                    Session ID
                  </Label>
                  <p className="text-sm font-mono mt-1 break-all leading-relaxed">
                    {httpBridge.getSessionId()}
                  </p>
                </div>
              </div>

              <div className="p-4 bg-gray-50 dark:bg-gray-800/50 rounded-lg border">
                <div className="flex items-center justify-between">
                  <Label className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
                    Connection Status
                  </Label>
                  <span
                    className={`text-sm font-medium ${httpBridge.isListening() ? 'text-green-600' : 'text-red-600'}`}
                  >
                    {httpBridge.isListening() ? '🟢 Active' : '🔴 Inactive'}
                  </span>
                </div>
                <p className="text-sm text-muted-foreground mt-1">
                  HTTP Bridge is{' '}
                  {httpBridge.isListening()
                    ? 'actively listening for'
                    : 'not receiving'}{' '}
                  dApp requests
                </p>
              </div>
            </div>
          </details>
        </CardContent>
      </Card>
    </div>
  )
}
